### ISSUE TITLE
search

### ISSUE THREAD

**Issue by An1an1** [Zalexanninev15/WebWordSearch#2]
How to search also only on a multi-page site and to indicate the page number ?

**Comment by Zalexanninev15** [comment]
If I understand correctly, then you need to replace this `url_list = [row.strip() for row in file]` string with a page search. Or get all the pages of the site by links and write their file, and then just run the script. 

In general, I advise you to look for a better implementation, I did this already 2 years ago, when I didn't really know Python (although I'm still learning it now). I advise you to contact ChatGPT with such a request and attach the code from the script from the repository of this site..

**Comment by An1an1** [comment]
Ok, thank you!

**Comment by Zalexanninev15** [comment]
I can offer another script (https://github.com/Zalexanninev15/rayman-scanner) of mine, there is an extraction of internal site links. I think you will find what you need and adapt it for yourself.
